### ISSUE TITLE
For loop in `off` is unecessary?

### ISSUE THREAD

**Issue by kiasaki** [marionebl/nano-event-emitter#1]
Hey there, I was looking for a minimalistic event emitter implementation to base mine off and yours seems pretty small with no extra features, I love it.

Although, I think that you have a `forEach` that has no use in the `off` function, here:

https://github.com/marionebl/nano-event-emitter/blob/master/src/index.js#L18

Am I mistaken of simply removing the forEach and leaving the code inside would still work?

**Comment by hawkerboy7** [comment]
Indeed I noticed this as well while checking the code.
The `if (! listener) { delete this.observers[event]; }` can be placed outside the loop.

I've worked on a mini-event-listener before is saw this code. Maybe you can take a look. It also has some checks to ensure you don't do things that you shouldn't. It should help you to debug your code because you can also enable logging of events and possible error's you've created. [MiniEventEmitter](https://github.com/hawkerboy7/mini-event-emitter)

**Comment by marionebl** [comment]
Thanks for the heads up guys!
Fixed in release 0.1.0: https://github.com/marionebl/nano-event-emitter/releases/tag/v0.1.0

**Comment by hawkerboy7** [comment]
np ;)
